# Use Python 3.11 as the base image
FROM python:3.11-slim

# Set working directory inside the container
WORKDIR /backend

# Copy only the requirements file first (better caching)
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the backend folder
COPY . .


# Expose the application port
EXPOSE 8000

# Run the application
CMD ["python", "-m", "app.main"]
